# ===============================
# CONEXIÓN A LA BASE DE DATOS NEON
# ===============================
spring.datasource.url=Pega_AQUI_tu_URL_de_Neon
spring.datasource.username=Pega_AQUI_tu_usuario_de_Neon
spring.datasource.password=jdbc:postgresql://ep-dawn-night-an2au2vx-pooler.c-6.us-east-1.aws.neon.tech/sanos_y_salvos_db?user=neondb_owner&password=npg_nGytqPe5RDo6&sslmode=require&channelBinding=require

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true